### PR TITLE
Bump ujson>=2.0.3 to avoid memleak

### PR DESCRIPTION
**Pull request by mrunge**
For details, see https://github.com/ultrajson/ultrajson/pull/394

### CODE REVIEW

**Comment by jd** [comment]
Requirements are made for API compat, not for listing bug fixes.
Obviously you need to use latest version to have all the bug fixes 🤷

**Comment by mrunge** [comment]
I agree. This here is mostly to prevent folks from running into an issue with a memory leak. For testing, this should be using ujson 4 (or whatever is current).

**Comment by tobias-urdin** [comment]
I kind of agree that we should not do that, anyways, CI is broke and needs fixing.

**Comment by tobias-urdin** [comment]
ci is fixed, and this change is not needed

**Pull request closed without merging**
