### PR TITLE
Remove hacking dependency for pep8

### PR DESCRIPTION
**Pull request by jd**
Hacking is not maintained and depends on an old flake8 version.
Switch to flake8 and a few standard extensions.

### CODE REVIEW

**Comment by jd** [comment]
Pull-request updated, HEAD is now 6362f56a09a33807aa74411cad8a1deb06a7e6fd

**Comment by chungg** [comment]
what's with all the newlines between 3rd party libs?

**Comment by jd** [comment]
They're grouped by lib. *shrugs*

**Comment by chungg** [comment]
oh. you can change the style for flake8-import-order (https://github.com/PyCQA/flake8-import-order#styles) i think we want something like `google`,  `smarkets `, `appnexus`.

or if the new lines per lib doesn't bother you, keep it as is.

**Comment by jd** [comment]
Yeah that don't really bother me. I'll rebase.

**Comment by jd** [comment]
Pull-request updated, HEAD is now 0b5ca32c6b8b892ca146a2fcd595f8e615ba2884

**Pull request merged**
