### PR TITLE
Replace oslotest by testtools

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by jd** [comment]
Pull-request updated, HEAD is now 7064fcacced7198fddf9007e41438375b990083c

**Comment by jd** [comment]
@sileht we could maybe move some to testtools?

**Comment by chungg** [comment]
errr.. now i'm worried. what was the OS_* stuff doing?

**Comment by sileht** [comment]
@chungg by default testtools capture stdout and stderr and print them only if the test fail. Sometimes is cool to print it instantly, for example when tests hang.

**Pull request merged**
