### PR TITLE
Remove __version__ from gnocchiclient module

### PR DESCRIPTION
**Pull request by jd**
It's not used.

### CODE REVIEW

**Comment by jd** [comment]
Why? it exists and is fine.

**Comment by chungg** [comment]
oh, you did the opposite as what we did in the other clients... i think it makes better sense to keep the copy in __init__ and remove the version.py we have instead

**Comment by jd** [comment]
It takes >1s to to read the version info from pbr. Doing it each time you import anything from `gnocchiclient` is not a good idea.

**Comment by chungg** [comment]
... wtf is pbr doing?

**Pull request merged**
